stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  profile: "D01"

build-D01:       # This job runs in the build stage, which runs first.
  stage: build
  only: 
    variables: 
      - $profile == "D01" && $CI_PIPELINE_SOURCE == "web"
  tags: 
    - abD01Wms01
  script:
    - chmod u+x mvnw
    - ./mvnw -P$profile clean package

deploy-D01:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  variables: 
    GIT_STRATEGY: none 
  only: 
    variables: 
      - $profile == "D01" && $CI_PIPELINE_SOURCE == "web"
  tags: 
      - abD01Wms01
  script:
    - mkdir -p ~gitlab-runner/apps
    - cp target/*.jar ~gitlab-runner/apps/apps.jar
    - cd ~gitlab-runner/apps
    - if [ -f run.pid ]; then kill `cat run.pid `; fi
    - sleep 30
    - nohup java -jar -Dspring.profiles.active=$profile apps.jar >> apps.log 2>&1 & echo $! > run.pid
