# 로그 레벨
logging:
  level:
    kr.co.seculink: debug
  config: classpath:logback-spring-D01.xml

# spring profile
spring:
  config:
    activate:
      on-profile: D01
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://abd01.cluster-czdogjjomgak.ap-northeast-2.rds.amazonaws.com:5432/abd01dsv?currentSchema=absv
      username: masteraccount
      password: TLZBFLDZM1!
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  redis:
    host: localhost
    port: 16379

server:
  port: 8080

jwt:
  token:
    header: Authorization
    role: USER
    issuer: seculink
    clientId: aiband
    expirySeconds: 31536000

upload:
  prof: /upload/
  event: /upload/
  temp: /upload/
  hwork: /upload/

eureka:
  client:
    service-url:
      defaultZone: http://ip-172-31-38-229.ap-northeast-2.compute.internal:8761/eureka
    register-with-eureka: true    # 유레카 서버에 서비스 등록
    fetch-registry: true          # 레지스트리 정보를 로컬에 캐싱