# 로그 레벨
logging:
  level:
    kr.co.seculink: debug
  config: classpath:logback-spring-D01.xml

# spring profile
spring:
  config:
    activate:
      on-profile: D01
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://abd01.cluster-czdogjjomgak.ap-northeast-2.rds.amazonaws.com:5432/abd01dsv?currentSchema=absv
    username: masteraccount
    password: TLZBFLDZM1!

server:
  port: ${SERVER_PORT:8080}

