# 로그 레벨
logging:
  level:
    kr.co.seculink: debug
  config: classpath:logback-spring-D01.xml

# spring profile
spring:
  config:
    activate:
      on-profile: D01
  datasource:
    hikari:
      writer-dif:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://abd01.cluster-czdogjjomgak.ap-northeast-2.rds.amazonaws.com:5432/abd01dif?currentSchema=abif
        username: masteraccount
        password: TLZBFLDZM1!
        maximum-pool-size: 4
      reader-dif:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://abd01.cluster-ro-czdogjjomgak.ap-northeast-2.rds.amazonaws.com:5432/abd01dif?currentSchema=abif
        username: masteraccount
        password: TLZBFLDZM1!
        maximum-pool-size: 4
      writer-dsv:
        driver-class-name: org.postgresql.Driver
#        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:postgresql://abd01.cluster-czdogjjomgak.ap-northeast-2.rds.amazonaws.com:5432/abd01dsv?currentSchema=absv
#        jdbc-url: jdbc:log4jdbc:postgresql://abd01.cluster-czdogjjomgak.ap-northeast-2.rds.amazonaws.com:5432/abd01dsv?currentSchema=absv
        username: masteraccount
        password: TLZBFLDZM1!
        maximum-pool-size: 4
      reader-dsv:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://abd01.cluster-ro-czdogjjomgak.ap-northeast-2.rds.amazonaws.com:5432/abd01dsv?currentSchema=absv
        username: masteraccount
        password: TLZBFLDZM1!
        maximum-pool-size: 4
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  redis:
    host: abd01dch.ft8b8b.0001.apn2.cache.amazonaws.com
    port: 6379

server:
  port: 8080

jwt:
  token:
    header: Authorization
    role: USER
    issuer: seculink
    clientId: aiband
    expirySeconds: 31536000

upload:
  prof: /upload/
  event: /upload/
  temp: /upload/
  hwork: /upload/

eureka:
  client:
    service-url:
      defaultZone: http://ip-172-31-38-229.ap-northeast-2.compute.internal:8761/eureka
    register-with-eureka: true    # 유레카 서버에 서비스 등록
    fetch-registry: true          # 레지스트리 정보를 로컬에 캐싱